config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :user_preferred_locations
    resources :locations
    resources :chairs
    resources :availabilities
    resources :branches
    resources :shifts
    resources :deputy_roles

    root to: "users#index"
  end

  devise_for :users

  resources :user_preferred_locations, only: %i(new create)
  
  resources :availabilities, only: %i(index new create destroy) do
    collection do
      get 'export', to: 'availabilities#availabilities_csv'
      delete 'delete', to: 'availabilities#delete_all'
      post 'calendar_create', to: 'availabilities#calendar_create'
      get 'calendar', to: 'availabilities#calendar'
    end
  end

  resources :shifts do
    collection do
      post 'calendar_create', to: 'shifts#calendar_create'
      get 'deputy_export', to: 'shifts#deputy_export'
    end
  end

  resources :admin_dashboard, only: [:heatmap, :users] do
    collection do
      get 'heatmap', to: 'admin_dashboards#heatmap'
      get 'users', to: 'admin_dashboards#users'
      get 'scheduling', to: 'admin_dashboards#scheduling'
    end
  end

  get '/heartbeat' => 'heartbeat#show'

  resources :user, only: [:show, :edit, :update, :destroy] do
    member do
      post 'submit', to: 'user#submit'
    end
  end

  resources :dashboards, only: [:index] do
    collection do
      get 'unsubmitted_report'
    end
  end


  unauthenticated :user do
    root to: 'dashboards#unauthenticated', as: 'landing_page'
  end
  root to: 'dashboards#index'
  
  get 'dashboards/email_incomplete', to: 'dashboards#email_incomplete', as: 'email_incomplete'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_preferred_location.rb
# frozen_string_literal: true

# The model to hold student preferences for working location hours
class UserPreferredLocation < ApplicationRecord
  belongs_to :user
  belongs_to :location

  # rubocop: disable Rails/UniqueValidationWithoutIndex
  validates :location,
            uniqueness:
              { scope: :user_id,
                message:
                'For each user, only one record may exist per location.' }
  # rubocop: enable Rails/UniqueValidationWithoutIndex
  validates :preferred_hours, presence: true

  attr_accessor :no_preference
end

app/controllers/admin/user_preferred_locations_controller.rb
# frozen_string_literal: true

module Admin
  class UserPreferredLocationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions
    # to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/user_preferred_locations_controller.rb
# frozen_string_literal: true

# Controller to manage user preferred locations
class UserPreferredLocationsController < ApplicationController
  prepend_before_action :setup_user

  def new
    set_upls if @user.branch.present?
  end

  def create
    obj = UserPreferredLocationCreator.new(params: upl_params, user: @user)
    if obj.call
      redirect_to calendar_availabilities_path,
                  notice: 'Successfully saved location preferences!'
    else
      flash_alerts(obj)
      @upls = obj.upls
      render 'new'
    end
  end

  private

  def setup_user
    @user = current_user
  end

  def set_upls
    if @user.branch&.ct?
      set_ct_upl
    else
      set_other_upls
    end
  end

  def set_ct_upl
    @upls = helpers.get_preferred_location(@user)
  end

  # for STs and MTs
  def set_other_upls
    # upls already exist
    @upls = UserPreferredLocation.where(user: @user).order(:location_id)
    return unless @upls.length != @user.branch.locations.length

    # need to initialize new upls
    @upls = @user.branch.locations.map do |l|
      UserPreferredLocation.new(location: l, preferred_hours: 0)
    end
  end

  def upl_params
    params.require(:user_preferred_location).permit(
      :no_preference, branch_specific_params
    )
  end

  def branch_specific_params
    # CTs do not provide preferred hours
    return :location_id if @user.branch.ct?

    # for each location, permit location_id => preferred_hours
    @user.branch.locations.map { |loc| [loc.id.to_s, :preferred_hours] }.to_h
  end

  def authorize!
    authorize UserPreferredLocation.new
  end
end

app/helpers/user_preferred_locations_helper.rb
# frozen_string_literal: true

# Helper methods for the upl views
module UserPreferredLocationsHelper
  # for CTs
  # their preferred location is the one with the highest preferred hours
  def get_preferred_location(user)
    user.user_preferred_locations.order(preferred_hours: :desc)
        .first_or_initialize
  end
end

app/views/user_preferred_locations/_index.html.erb
<div class="container">
  <% if user.user_preferred_locations.empty? %>
    No preference
  <% elsif user.branch&.ct? %>
    <strong>Preferred Location:</strong>
    <span><%= get_preferred_location(user).location&.name %></span>
  <% else %>
    <% user.user_preferred_locations.each do |upl| %>
      <strong><%= upl.location.name %>:</strong>
      <span><%= hours_string(upl.preferred_hours) %></span>
      <br>
    <% end %>
  <% end %>
</div>

app/views/user_preferred_locations/new.html.erb
<%= javascript_pack_tag 'upl_form' %>

<%= render 'application/student_step_bar', active: 2, user: @user %> 

<div class="container">
  <h2>Add Location Preferences</h2>
  <% if @user&.branch.present? %>
    <p><b>Branch: </b><%= @user.branch.full_title %></p>
  <% end %>

  <% if @user&.branch&.ct? %>
    <%= form_for @upls, url: user_preferred_locations_path, method: 'post' do |f| %>
      <div class="form-group">
        <label class="location_pref_obj">
          Preferred Location
          <%= f.collection_select :location_id, @user.branch.locations, :id, :name, { include_blank: true }, { id: 'location_pref', class: 'location_pref_obj form-control' } %>
        </label>
      </div>
      <label>
        <%= f.check_box :no_preference %>
        No Location Preference
      </label>
      <div class='mt-3' role="navigation">
        <%= link_to "Back", edit_user_path(current_user), type: 'button', class: "btn btn-secondary btn-lg"%>
        <%= submit_tag 'Next' , class: 'btn btn-yale btn-lg'%>
      </div>
    <% end%>

  <% elsif @user&.branch&.locations.present? %>
    <p>
      <b>Requested hours: </b><%= @user.min_hours %> to <%= @user.max_hours %>
      <br>
      The sum of the hours you choose for each location should fall in the range of your requested hours.
    </p>
    
    <div class="form-group"> 
      <%= form_for :user_preferred_location, url: user_preferred_locations_path do |f| %>
        <p>Number of hours you would like to work in each location:</p>
        <div class="form-row">
          <% @upls.each do |upl| %>
            <%= f.fields_for "[#{upl.location.id}]", upl do |ff|%>
              <label class='location_pref_obj form-group col'>
                <%= upl.location.name%>
                <%= ff.number_field :preferred_hours,
                    min: 0, max: 19, 
                    id: "location_pref_#{upl.location.id}",
                    class: 'location_pref_obj form-control',
                    'aria-label': "preferred hours for #{upl.location.name}" %>  
              </label>
            <% end%>
          <% end %>
        </div>
        <label>
          <%= f.check_box :no_preference %>
          No Location Preference
        </label>
        <div class='mt-3' role="navigation">
          <%= link_to "Back", edit_user_path(current_user), type: 'button', class: "btn btn-secondary btn-lg"%>
          <%= submit_tag 'Next' , class: 'btn btn-yale btn-lg'%>
        </div>
      <% end%>
    </div>
  <% elsif @user.branch.present? %>
    <p>No locations. Please click next.</p>
    <div role="navigation">
      <%= link_to 'Back', edit_user_path(@user), type: 'button', class: 'btn btn-secondary btn-lg'%>
      <%= link_to 'Next', calendar_availabilities_path, type: 'button', class: 'btn btn-yale btn-lg'%>
    </div>
  <% else %>
    <p>Please select your branch in the user profile.</p>
    <div role="navigation">
      <%= link_to 'Back', edit_user_path(@user), type: 'button', class: 'btn btn-secondary btn-lg'%>
    </div>
  <% end %>
</div>