config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :user_preferred_locations
    resources :locations
    resources :chairs
    resources :availabilities
    resources :branches
    resources :shifts
    resources :deputy_roles

    root to: "users#index"
  end

  devise_for :users

  resources :user_preferred_locations, only: %i(new create)
  
  resources :availabilities, only: %i(index new create destroy) do
    collection do
      get 'export', to: 'availabilities#availabilities_csv'
      delete 'delete', to: 'availabilities#delete_all'
      post 'calendar_create', to: 'availabilities#calendar_create'
      get 'calendar', to: 'availabilities#calendar'
    end
  end

  resources :shifts do
    collection do
      post 'calendar_create', to: 'shifts#calendar_create'
      get 'deputy_export', to: 'shifts#deputy_export'
    end
  end

  resources :admin_dashboard, only: [:heatmap, :users] do
    collection do
      get 'heatmap', to: 'admin_dashboards#heatmap'
      get 'users', to: 'admin_dashboards#users'
      get 'scheduling', to: 'admin_dashboards#scheduling'
    end
  end

  get '/heartbeat' => 'heartbeat#show'

  resources :user, only: [:show, :edit, :update, :destroy] do
    member do
      post 'submit', to: 'user#submit'
    end
  end

  resources :dashboards, only: [:index] do
    collection do
      get 'unsubmitted_report'
    end
  end


  unauthenticated :user do
    root to: 'dashboards#unauthenticated', as: 'landing_page'
  end
  root to: 'dashboards#index'
  
  get 'dashboards/email_incomplete', to: 'dashboards#email_incomplete', as: 'email_incomplete'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin_dashboards_controller.rb
# frozen_string_literal: true

# Controller for admin dashboard
class AdminDashboardsController < ApplicationController
  # rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
  def scheduling
    locs = Location.where(branch: current_user.branch)
    @location = locs.find_by(id: params[:location])
    @selected_chair = @location.chairs.find_by(id: params[:chair]) if @location
    @location ||= locs.first

    @users = helpers.users_sorted_by_availability(@location, @selected_chair)

    @selected_user = @location.branch.users.find_by(id: params[:user])
    @availabilities = @selected_user.availabilities if @selected_user
    @scheduled_users = (@selected_chair&.shifts || []).map(&:user).uniq
    return if @scheduled_users.include?(@selected_user)

    @scheduled_users << @selected_user if @selected_user
  end

  # rubocop:enable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity

  def heatmap
    @all_users = User.where(branch_id: current_user.branch_id)
    return unless params.key?(:slot_id)

    @slot = Slot.from_id(params[:slot_id])
    @available_students = []
    @all_users.each do |s|
      @available_students << s if s.covers_timeslot?(@slot)
    end
  end

  def users
    @users = User.where(branch_id: current_user.branch_id)
    return unless params.key?(:user_id)

    @selected_user = User.find(params[:user_id])
    @availabilities = Availability.where(user_id: params[:user_id])
  end

  def authorize!
    authorize (current_user || User.new), :admin?
  end
end

app/helpers/admin_dashboards_helper.rb
# frozen_string_literal: true

# Helper methods for Admin Dashboard views
# rubocop:disable Metrics/ModuleLength
module AdminDashboardsHelper
  SELECTED_USER_CLASS = 'selected'

  def scheduling_calendar_styling(location, users)
    lambda do |id|
      chair = location.chairs.find { |c| c.covers_timeslot?(Slot.from_id(id)) }
      return {} unless chair

      ids = chair.slots.map(&:to_id)
      style = progress_style(chair, users) if id == ids.first

      { class: scheduling_calendar_classes(id, ids, users), style: style }
    end
  end

  def scheduling_calendar_classes(id, ids, users)
    classes = case id
              when ids.first then %w(chair top-of-chair)
              when ids.last then %w(chair bottom-of-chair)
              else %w(chair)
              end

    classes << 'no-avail-alert' if available_users_slot(users, id).empty?
    classes
  end

  # rubocop:disable Metrics/MethodLength
  def scheduling_calendar_inner_html(location, selected_user, users)
    lambda do |id|
      chair = location.chairs.find { |c| c.covers_timeslot?(Slot.from_id(id)) }
      opts = { location: location, user: selected_user }
      opts[:chair] = chair
      url = scheduling_admin_dashboard_index_url(opts)
      text = if chair && id == chair.slots.first.to_id
               progress_text(chair, users)
             else
               '&nbsp;'
             end

      return "<a href='#{url}' style='text-decoration:none;'>
                <div style='height:100%;width:100%'>#{text}</div>
              </a>".html_safe
    end
  end
  # rubocop:enable Metrics/MethodLength

  # text summarizing scheduling progress to display on chair calendar
  def progress_text(chair, users)
    if chair.location.continuous
      format('%<filled_slots>d/%<tot_slots>d filled (%<avail>d available)',
             filled_slots: chair.filled_slots(users),
             tot_slots: chair.slots.size,
             avail: chair.num_available(users))
    else
      format('%<tot_hrs>0.1f scheduled hours(s) (%<lead_hrs>0.1f lead hours)',
             lead_hrs: chair.lead_hrs, tot_hrs: chair.tot_hrs)
    end
  end

  # generate scheduling progress bar style for chair calendar
  def progress_style(chair, users)
    return unless chair.location.continuous

    filled_pct = 100 * chair.filled_slots(users) / chair.slots.size
    "background:
       linear-gradient(to right,
                       lightgreen #{filled_pct}%,
                       lightgrey #{filled_pct}%)"
  end

  def heatmap_calendar_inner_html(id)
    "<a href='/admin_dashboard/heatmap?slot_id=#{id}'
          style='display:block;text-decoration:none;'
          id=#{id}_link>
        <div style='height:100%;width:100%'>
          &nbsp;
        </div>
    </a>".html_safe
  end

  def heatmap_calendar_styling(users)
    lambda do |id|
      slot = Slot.from_id(id)
      count = 0
      (users || []).each do |s|
        count += 1 if s.covers_timeslot?(slot)
      end

      count.positive? ? { class: "heatmap-color-#{count}" } : {}
    end
  end

  # rubocop:disable Metrics/MethodLength
  # rubocop:disable Style/GuardClause
  def shift_scheduling_styling(loc)
    lambda do |id, user, selected|
      shift = user.scheduled?(id)
      classes = selected ? [SELECTED_USER_CLASS] : []
      return { class: classes << UNAVAIL_STR } unless user.covers_timeslot?(Slot.from_id(id))

      if shift
        if shift.chair.location == loc
          return { class: classes << SCHEDULED_HERE_CLASS }
        else
          return { class: classes << SCHEDULED_CLASS,
                   'data-toggle' => 'tooltip',
                   'title' => shift.chair.location.name }
        end
      end
      classes << PAINTABLE_STR if selected
      { class: classes }
    end
  end
  # rubocop:enable Metrics/MethodLength
  # rubocop:enable Style/GuardClause

  def mini_calendar_styling(user)
    lambda do |id|
      av = user.availabilities.find { |a| a.covers_timeslot?(Slot.from_id(id)) }
      return {} unless av

      ids = av.slots.map(&:to_id)

      classes = user.scheduled?(id) ? %w(mini-scheduled) : %w(mini-available)
      classes << 'mini-top' if id == ids.first
      classes << 'mini-bottom' if id == ids.last
      { class: classes }
    end
  end

  def location_options(branch)
    branch.locations.map do |loc|
      [loc.name, scheduling_admin_dashboard_index_url(location: loc)]
    end
  end

  def available_users(users, selected_chair)
    users.filter { |u| u.available_during?(selected_chair) }
  end

  def available_users_slot(users, slot_id)
    users.filter do |u|
      u.covers_timeslot?(Slot.from_id(slot_id)) && !u.scheduled?(slot_id)
    end
  end

  def formatted_user_table(users)
    users.map do |u|
      if u.target_hours.nil? || u.target_hours.zero?
        { user: u, msg: 'Form incomplete' }
      else
        { user: u, msg: "#{u.mins_covered * 100 /
                                           (u.target_hours * 60)}%" }
      end
    end
  end

  def user_link(user:, chair:, location:)
    # if the user is currently selected, clicking on it should deselect it
    user = nil if selected?(user&.id, :user)
    scheduling_admin_dashboard_index_url(user: user,
                                         chair: chair, location: location)
  end

  def selected?(id, param)
    params[param].to_i == id
  end

  # @param show [Boolean] whether the button should be visible and active
  # @param value [String] the icon that the button should display
  def icon_button(show, id = nil, classes = [])
    classes.append(show ? '' : 'invisible')
    "<i id='#{id}' class='#{classes.join(' ')}'></i>".html_safe
  end

  def users_sorted_by_availability(location, chair)
    users = location.branch.users.order(last_name: :asc)
    return users unless chair

    available_users = users.select { |u| u.available_during?(chair) }
    available_users + (users - available_users)
  end

  def user_list_greyed_out(user, chair)
    !chair.nil? && !user.available_during?(chair)
  end
end
# rubocop:enable Metrics/ModuleLength

app/views/admin_dashboards/_shift_calendar.html.erb
<div id="cal_div" class="container" >
  <table class="table calendar-table" id="<%= table_id %>">
    <thead>
      <tr>
        <th scope="col" id="time_header"></th>
	<th> Available
	  <button type="button" id="collapse-details">collapse</button>
	  <button type="button" id="expand-details">expand</button>
	</th>
	<% if selected_user %>
           <%= content_tag :th, selected_user.full_name,
	                        class: 'selected' %>
        <% end %>
	<th> Scheduled </th>   
      </tr>
    </thead>
    <tbody>
      <% times(time_range).each do |time| %>
        <tr id="t<%= time %>">
          <% if time_displayed?(time) %>
            <th scope="row"><%= display_time(time) %></th>
          <% else %>
            <th scope="row">&nbsp</th>
          <% end %>

	  <% id = time_to_id(day, time) %>
	  <% available = available_users_slot(users, id) %>
	  <% if available.empty? %>
	    <td></td>
	  <% else %>
	    <td>
	      <details>
		<summary>
		  <%= available.size %> available
		</summary>
	          <% available.each do |user| %>
	            <%= link_to user.full_name, user_link(user: user, chair: selected_chair, location: location) %>
	          <% end %>
	      </details>
	    </td>
	  <% end %>

	  <% if selected_user %>
	    <%= content_tag :td, '', {id: id}.merge(styling.call(id, selected_user, true)) %>
	  <% end %>

	  <% scheduled = users.filter { |u| u.scheduled?(id) } %>
	  <% if scheduled.empty? %>
	    <td></td>
	  <% else %>
	    <% scheduled.each do |u| %>
	      <td> <%= u.full_name %> </td>
	    <% end %>
	  <% end %> 
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin_dashboards/_user_panel.html.erb
<div
  <% if !@selected_chair.nil? && !selected_user.available_during?(@selected_chair)%>
    class="greyed-out"
  <% end %>>
  <h3>
    Availability
  </h3>
  <ul>
    <% if availabilities.empty? %>
      <p>None</p>
    <% else %>
      <% availabilities.each do |avail| %>
        <li> <%= avail.day %> <%= display_time(avail.start_time) %> to 
        <%= display_time(avail.end_time) %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/admin_dashboards/_users_list.html.erb
<%= javascript_pack_tag 'user_list' %>

<div class='users-list'>
  <div id='users-list-header'>
    <div class='mb-1'><b>Employees</b></div>
    <div id='filter'>
      <i id='filter-icon' class="fas fa-filter"></i>
      <select id='filter-dropdown'>
        <option selected value='last_name'>Sort by...</option>
        <option value='special_requests'>Special request</option>
        <option value='hour_differential'>Hour differential</option>
        <option value='lead'>Position</option>
      </select>
    </div>
  </div>
  <div id="accordion">
    <% users.each_with_index do |user, index| %>
      <div class="<%= "card #{ user == selected_user ? 'selected-user': ''} #{ user_list_greyed_out(user, @selected_chair) ? 'greyed-out' : ''}"%>" id="u<%= index %>" data-info="<%= user.to_json %>" data-scheduled="<%= user.mins_covered.to_json %>">
        <a href="<%= user_link(user: user, chair: selected_chair, location: location) %>" class='user'>
          <div class="card-header mb-0" id='<%= "heading#{index}" %>'>
            <div>
              <div aria-expanded="<%= selected?(user.id, :user) %>" aria-controls='<%= "collapse#{index}" %>'>
                <div class="user__heading">
                  <div class="user__heading--top-row">
                    <span>
                      <%= user.full_name %>
                    </span>
                  </div>
                  <div>
                    <%= user.mins_covered / 60.0 %>/<%= user.target_hours.present? ? user.target_hours : 'None' %>
                  </div> 
                  <div id='special-request-<%=index%>' class="special-request-text collapse"><%= user.special_requests %></div>
                </div>
              </div>
            </div>
            <div class='icon-wrapper'>
              <%= icon_button(user.lead?, id=nil, classes=['fas', 'fa-heading', 'lead-icon']) %>
              <%= icon_button(user.special_requests.present?, id="icon-#{index}", classes=['fas', 'fa-star', 'special-request-icon']) %>
            </div> 
          </div>
          <div id='<%= "collapse#{index}" %>' class="<%= selected?(user.id, :user) ? '' : 'collapse' %>" aria-labelledby='<%= "heading#{index}" %>'>
            <div class="card-body" style="overflow: hidden">
	      <% if user == selected_user %>
              <%= render partial: 'application/calendar_bare',
		  locals: {
		  table_id: 'mini-calendar',
		  display_times: [800,1200, 1700],
		  time_disp_abbrev: true,
		  day_names: %w( S M T W T F S ),
		  styling: mini_calendar_styling(selected_user),
		  }%>
	      <% end %>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/admin_dashboards/heatmap.html.erb
<div style="display:inline-block; float:left; 
  width:80%; padding-bottom:80px" > 
  <h1>Heatmap</h1>
  <%= render :partial => 'application/calendar_bare', 
  :locals => {:styling => heatmap_calendar_styling(@all_users),
              inner_html: method(:heatmap_calendar_inner_html) }  %>
</div>

<div style="display:inline-block; float:right;
  width:20%; margin-top:5%;">
  <% if @slot && @available_students %>
    <h2>Slot: <%= @slot.to_s %> </h2>
    <h3> Available students:</h3>
    <% if @available_students.length > 0 %>
      <ul>
      <% @available_students.each do |s| %>
        <li><%= s.first_name %> <%= s.last_name %> </li>  
      <% end %>
      </ul>
    <% else %>
      <h3> None </h3>
    <% end %>
  <% end %>
</div>

app/views/admin_dashboards/scheduling.html.erb
<% unless @selected_chair.nil? || @selected_user.nil? %>
  <%= javascript_pack_tag 'shift_creation_calendar' %>
<% end %>

<%= javascript_pack_tag 'chair_view' %>

<div id="grid-wrapper" class='container-fluid'>
  <div id="users-list">
    <%= render partial: 'users_list', locals: { selected_user: @selected_user,
	                                        users: @users,
                                                selected_chair: @selected_chair,
                                                location: @location }%>
  </div>
  
  <div id="sched-select-container" class="container">
    <%= select_tag("locations", options_for_select(location_options(@location.branch), scheduling_admin_dashboard_index_url(location: @location)), onchange: "window.location.href=this.value") %>
  </div>


  <% if @selected_chair %>
    <span id="sched-panel">
      <%= form_with(url: "/shifts/calendar_create.json",
                   method: "post",
                   html: { id: "shift-creation-form" },
                   local: "true") do |form| %>
        <h2> <%= Slot.from_chair(@selected_chair).to_s%> </h2>
        <%= render partial: 'shift_calendar',
            locals: {
	      users: @users,
	      scheduled_users: @scheduled_users,
	      day: Chair.days[@selected_chair.day],
	      selected_user: @selected_user,
              time_range: (@selected_chair.start_time...@selected_chair.end_time),
              table_id: "shifts-calendar",
              styling: shift_scheduling_styling(@location),
	      selected_chair: @selected_chair,
	      location: @location}  %>
        <% if @selected_user %>
          <%= hidden_field_tag 'location', @location.id %>
          <%= hidden_field_tag 'user', @selected_user.id %>
          <%= hidden_field_tag 'chair', @selected_chair.id %>
          <%= form.submit "Save", class: 'btn btn-primary' %>
        <% end %>
      <% end %>
      <%= link_to('Done',
	  scheduling_admin_dashboard_index_url(location: @location,
	  user: @selected_user), id: 'chair-done', class: 'btn btn-primary') %>
    </span>
    <% else %>
      <span id="sched-calendar">
      <%= render partial: 'calendar_bare',
          locals: { styling: scheduling_calendar_styling(@location, @users),
          inner_html: scheduling_calendar_inner_html(@location, @selected_user, @users),
          table_id: 'chairs-calendar' } %>
      </span>
    <% end %>
</div>

app/views/admin_dashboards/users.html.erb
<h1> Admin Dashboard - Users </h1>

<div style="display:inline-block; float:left; 
  width:60%; padding-bottom:80px; overflow: auto; height: 100vh" >
  <table id="admin-dashboard-users">
    <thead>
      <tr>
        <th scope='col'>Users</th>
        <th scope='col'>Percent of target hours</th>
        <th scope='col'>Name</th>
      </tr>
    </thead>
    <tbody>
      <% formatted_user_table(@users).each do |row| %>
        <% user = row[:user]%>
        <tr>
          <td> <%= user.username %> </td>
          <td> <%= row[:msg] %> </td>
          <td>
            <% if user.first_name.present? && user.last_name.present? %>
              <a href="<%= users_admin_dashboard_index_url(user_id: user.id) %>"
                  id="user_id_<%= user.id %>">
                <%= user.first_name%> <%= user.last_name %>
              </a>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div style="display:inline-block; float:right; 
  width:40%; margin-top:-3%; padding-left:30px">
  <% if @selected_user %>
    <h3>
      <%= @selected_user.first_name %> <%= @selected_user.last_name %>'s 
      Availabilities
    </h3>
    <ul>
      <% if @availabilities.empty? %>
        <p>None</p>
      <% else %>
        <% @availabilities.each do |avail| %>
          <li> <%= avail.day %> <%= display_time(avail.start_time) %> to 
          <%= display_time(avail.end_time) %></li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
</div>