config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :user_preferred_locations
    resources :locations
    resources :chairs
    resources :availabilities
    resources :branches
    resources :shifts
    resources :deputy_roles

    root to: "users#index"
  end

  devise_for :users

  resources :user_preferred_locations, only: %i(new create)
  
  resources :availabilities, only: %i(index new create destroy) do
    collection do
      get 'export', to: 'availabilities#availabilities_csv'
      delete 'delete', to: 'availabilities#delete_all'
      post 'calendar_create', to: 'availabilities#calendar_create'
      get 'calendar', to: 'availabilities#calendar'
    end
  end

  resources :shifts do
    collection do
      post 'calendar_create', to: 'shifts#calendar_create'
      get 'deputy_export', to: 'shifts#deputy_export'
    end
  end

  resources :admin_dashboard, only: [:heatmap, :users] do
    collection do
      get 'heatmap', to: 'admin_dashboards#heatmap'
      get 'users', to: 'admin_dashboards#users'
      get 'scheduling', to: 'admin_dashboards#scheduling'
    end
  end

  get '/heartbeat' => 'heartbeat#show'

  resources :user, only: [:show, :edit, :update, :destroy] do
    member do
      post 'submit', to: 'user#submit'
    end
  end

  resources :dashboards, only: [:index] do
    collection do
      get 'unsubmitted_report'
    end
  end


  unauthenticated :user do
    root to: 'dashboards#unauthenticated', as: 'landing_page'
  end
  root to: 'dashboards#index'
  
  get 'dashboards/email_incomplete', to: 'dashboards#email_incomplete', as: 'email_incomplete'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

# Controller to manage all user information
class DashboardsController < ApplicationController
  def index
    @user = current_user
  end

  def unauthenticated; end

  def unsubmitted_report
    authorize current_user, :admin?
    @unsubmitted_users = User.where(branch: current_user.branch,
                                    submitted: false)
  end

  def authorize!; end

  # rubocop:disable Metrics/MethodLength
  def email_incomplete
    find_incomplete_users
    unsent_emails = []
    @incomplete_users.each do |user|
      UserMailer.email_incomplete_user(user: user).deliver
    rescue StandardError
      unsent_emails.append(user.email)
    end
    if unsent_emails.empty?
      flash.notice = 'Successfully emailed students!'
    else
      flash.alert = "Failed to deliver emails to #{unsent_emails.join(', ')}"
    end
    redirect_to root_path
  end
  # rubocop:enable Metrics/MethodLength

  private

  def find_incomplete_users
    @incomplete_users = User.all.where(role: 'student',
                                       branch: current_user.branch,
                                       submitted: false)
  end
end

app/views/dashboards/_student_dashboard.html.erb
<%= render 'application/student_step_bar', active: 4, user: user %>
  
<div class="container">
  <h2>Review and Submit</h2>

  <% if user.submitted %>
    <div class="card">
      <div class="card-body locked-message">
        <p class="card-text">
        Your information is now locked. If you need to request a change, please contact your manager.
      </p>
      </div>
    </div>
  <% end %>

  <h3>User Information</h3>
  <%= render 'user/info', user: user %>

  <% if user.branch&.locations.present? %>
    <h3>Location Preferences</h3>
    <%= render 'user_preferred_locations/index', user: user %>
  <% end %>
  

  <h3>Availability</h3>
  <%= render 'availabilities/table', 
      availabilities: user.availabilities.order('day ASC, start_time ASC') %>
  <% if !user.submitted %>
    <%= form_tag submit_user_path(user), method: :post do %>
      <%= submit_tag 'Submit', class: 'btn btn-yale btn-lg',
        data: { confirm: 'Are you sure? This action cannot be undone.' } %>
    <% end %>
  <% end %>
</div>

app/views/dashboards/index.html.erb
<% if @user.student? %>
  <%= render 'dashboards/student_dashboard', user: @user %>
<% end %>

<div>
  <% if @user.admin? %>
    <%= button_to "Unsubmitted Report", unsubmitted_report_dashboards_path, method: 'get' %>
    <%= button_to "Send Reminder Email", email_incomplete_path, method: 'get', data: {confirm: "Are you sure? This action will email all users who have not yet submitted their information."} %>
  <% end %>
</div>

<div>
  <% if @user.admin? %>
    <%= button_to "Export availabilities", export_availabilities_path, method: 'get' %>
    <%= button_to("Delete all availabilities", delete_availabilities_path,
        method: 'delete', data: { confirm: 'Do you really want to delete all availabilities in your branch?'}) %>
    <%= button_to "Export shifts to Deputy", deputy_export_shifts_path, method: 'get' %>
  <% end %>
</div>

app/views/dashboards/unauthenticated.html.erb
<div class="container">
  <div class="jumbotron text-center">
    <h1>Welcome to Scheduler!</h1>
    <p>Some description text here.</p>
    <div class="row row-eq-height justify-content-center">
      <%= button_to 'Log in', new_user_session_path, :class => 'btn btn-lg btn-primary btn-blue-background btn-blue-outline'%>
    </div>
  </div>
</div>

app/views/dashboards/unsubmitted_report.html.erb
<h1> Unsubmitted Report </h1>

<div>
  <table id="unsubmitted-report">
    <thead>
      <tr>
        <th scope='col'>Username</th>
        <th scope='col'>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @unsubmitted_users.each do |user| %>
        <tr>
          <td> <%= user.username %> </td>
          <td>
            <% if user.first_name.present? && user.last_name.present? %>
              <%= user.first_name + user.last_name %>
            <% end %> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>