config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :user_preferred_locations
    resources :locations
    resources :chairs
    resources :availabilities
    resources :branches
    resources :shifts
    resources :deputy_roles

    root to: "users#index"
  end

  devise_for :users

  resources :user_preferred_locations, only: %i(new create)
  
  resources :availabilities, only: %i(index new create destroy) do
    collection do
      get 'export', to: 'availabilities#availabilities_csv'
      delete 'delete', to: 'availabilities#delete_all'
      post 'calendar_create', to: 'availabilities#calendar_create'
      get 'calendar', to: 'availabilities#calendar'
    end
  end

  resources :shifts do
    collection do
      post 'calendar_create', to: 'shifts#calendar_create'
      get 'deputy_export', to: 'shifts#deputy_export'
    end
  end

  resources :admin_dashboard, only: [:heatmap, :users] do
    collection do
      get 'heatmap', to: 'admin_dashboards#heatmap'
      get 'users', to: 'admin_dashboards#users'
      get 'scheduling', to: 'admin_dashboards#scheduling'
    end
  end

  get '/heartbeat' => 'heartbeat#show'

  resources :user, only: [:show, :edit, :update, :destroy] do
    member do
      post 'submit', to: 'user#submit'
    end
  end

  resources :dashboards, only: [:index] do
    collection do
      get 'unsubmitted_report'
    end
  end


  unauthenticated :user do
    root to: 'dashboards#unauthenticated', as: 'landing_page'
  end
  root to: 'dashboards#index'
  
  get 'dashboards/email_incomplete', to: 'dashboards#email_incomplete', as: 'email_incomplete'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  # All Administrate controllers inherit from this
  # `Admin::ApplicationController`, making it the ideal place
  # to put authentication logic or other before_actions.
  class ApplicationController < Administrate::ApplicationController
    include Pundit

    before_action :authorize!
    rescue_from Pundit::NotAuthorizedError do
      flash[:alert] = 'Sorry, you don\'t have permission to do that.'
      redirect_to(root_path)
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    def authorize!
      authorize(current_user || User.new, :admin?)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base class for all controllers
class ApplicationController < ActionController::Base
  # to be used when rendering, not redirecting
  include Pundit

  before_action :authorize!, unless: :public_action?
  rescue_from Pundit::NotAuthorizedError do
    flash[:alert] = 'Sorry, you don\'t have permission to do that.'
    redirect_to(root_path)
  end

  def flash_alerts(instance)
    instance.errors.full_messages.each do |message|
      flash.now[:alert] = message
    end
  end

  def after_sign_in_path_for(user)
    return root_path unless user.student?

    user.submitted ? root_path : edit_user_path(user)
  end

  private

  def public_action?
    devise_controller? || instance_of?(HeartbeatController)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper top level comment
module ApplicationHelper
  # @param hours [Integer]
  # generates string for displaying number of hours
  def hours_string(hours)
    is_plural = hours == 1 ? '' : 's'
    # if hours ends with .0, drop the .0
    hours = hours.to_i == hours ? hours.to_i : hours
    "#{hours} hour#{is_plural}"
  end
end

app/views/application/_calendar_bare.html.erb
<% days ||= (0..6) %>
<% time_range ||= (800...2400) %>
<% styling ||= proc { {} } %>
<% inner_html ||= proc { nil } %>
<% table_id ||= 'calendar-table' %>
<% display_times ||= times(time_range).filter { |t| time_displayed?(t) } %>
<% day_names ||= days.map {|x| Availability.days.keys[x]} %>
<% time_disp_abbrev ||= false %>
<div id="cal_div" class="container" >
  <table class="table calendar-table" id="<%= table_id %>">
    <thead>
      <tr>
        <th scope="col" id="time_header"></th>
        <% days.each_with_index do |day, index| %>
          <th scope="col" id="<%= day %>"><%= day_names[index] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% times(time_range).each do |time| %>
        <tr id="<%= time %>">
          <% if display_times.include?(time) %>
            <th scope="row"><%= display_time(time, abbreviated: time_disp_abbrev) %></th>
          <% else %>
            <th scope="row" class="times-not-displayed">&nbsp</th>  
          <% end %>
          <% days.each do |day| %>
            <% id = time_to_id(day, time) %>
            <%= content_tag :td, {id: id}.merge(styling.call(id)) do -%>
              <%= inner_html.call(id) %>
            <% end -%>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/application/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close notice">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class='footer text-muted'>
  <ul class='footer-list'>
    <span>
      <li>Built by the <%= link_to 'Yale Student Developer and Mentorship Program', 'https://yalestc.github.io', 'aria-label': 'Yale Student Developer and Mentorship Program (external link)' %></li>
    </span>
    <span class='right'>
      <li><%= link_to 'Accessibility at Yale', 'https://usability.yale.edu/web-accessibility/accessibility-yale', 'aria-label': 'Accessibility at Yale (external link)' %></li>
      <li><%= link_to 'Contact the developers at app-dev@yale.edu', 'mailto:app-dev@yale.edu'%></li>
    </span>
  <ul>
</footer>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand text-decoration-none">Scheduler</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path , class: "nav-link text-decoration-none" %>
      </li>
      <% if current_user&.admin? %>
        <%= link_to 'Schedule View', scheduling_admin_dashboard_index_path, class: "nav-link text-decoration-none" %>
        <%= link_to 'User View', users_admin_dashboard_index_path, class: "nav-link text-decoration-none" %>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in?%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-decoration-none" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username%>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.role == 'admin' %>
              <%= link_to "Profile", user_path(current_user) , class: "dropdown-item text-decoration-none" %>
              <%= link_to "Admin page", admin_root_path, class: "dropdown-item text-decoration-none" %>
              <div class="dropdown-divider"></div>
            <% end %>
            <%= link_to "Log Out", destroy_user_session_path , class: "dropdown-item text-danger text-decoration-none", method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link text-decoration-none" %>
        </li>
      <% end %>

    </ul>
</nav>

app/views/application/_student_step_bar.html.erb
<% if user && user.student? && !user.submitted %>
  <div class="row justify-content-center">
    <nav class="btn-group" aria-label="student form steps" role='list'>
      <%= link_to '1. Add User Information', edit_user_path(user),
        type: 'button', class: get_bar_class(1, active),
        'aria-current': active?(1, active) ? 'step' : '', role: 'listitem' %>
      <%= link_to '2. Add Location Preferences', new_user_preferred_location_path,      
        type: 'button', class: get_bar_class(2, active),
        'aria-current': active?(2, active) ? 'step' : '', role: 'listitem' %>
      <%= link_to '3. Add Availability', calendar_availabilities_path,
        type: 'button', class: get_bar_class(3, active),
        'aria-current': active?(3, active) ? 'step' : '', role: 'listitem' %>
      <%= link_to '4. Review and Submit', dashboards_path,
        type: 'button', class: get_bar_class(4, active),
        'aria-current': active?(4, active) ? 'step' : '', role: 'listitem' %>
    </nav>
  </div>
<% end %>